#!/bin/bash

#docker build --platform arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .
#docker build --platform amd64 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx rm builder
docker buildx create --name builder --driver docker-container --use
docker buildx inspect --bootstrap
docker buildx build --platform linux/amd64,linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .